# Issue作成時に自動的に作成されるブランチの名称ルールを設定する
# 利用できるプレースホルダー名は以下を参照ください。
# https://github.com/robvanderleek/create-issue-branch/blob/main/tests/test-fixtures/issues.assigned.json
# 例：'${issue.number}-${issue.title}'　→　”37-Issueのタイトル”　となる
branchName: 'issue-${issue.number}'

# プルリクエストのマージ後にIssueを自動的に閉じる機能の有効無効
# 自動的に閉じるには"issue-XX"あるいは"iXX"（XXはIssue番号）のようなブランチ名が設定されている必要がある。
autoCloseIssue: true

# ブランチ作成後に”Branch ${branchName} created!”とIssueのコメントに通知してくれる機能の有効無効
silent: false

