name: Build-SonarCloud

on: [push]
    
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner
    - name: Restore
      run: dotnet restore src/SlackNotification/SlackNotification.sln

    - name: Sonarscanner for dotnet
      uses: dotnet-sonarscanner@v2.3
      with:
        buildCommand: dotnet build src/SlackNotification/SlackNotification.sln --configuration Release --no-restore
        testCommand: dotnet test src/SlackNotification/SlackNotification.sln --no-build --verbosity normal
        projectKey: yus-sasaki_NugetSample
        projectName: NugetSample
        sonarOrganisation: yus-sasaki
        beginArguments: >
            /d:sonar.verbose="true"
            /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
            /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}