name: Build-SonarCloud

on: [push]
    
jobs:
  check:
    name: Build-SonarCloud
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      - name: Restore dependencies
        run: dotnet restore 
        working-directory: src/SlackNotification
      - name: Build
        run: dotnet build src/SlackNotification/SlackNotification.sln --no-restore
      - name: SonarCloudScan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}